version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kanastra
      POSTGRES_USER: kanastra
      POSTGRES_PASSWORD: kanastra

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://kanastra:kanastra@db/kanastra

  frontend:
    build: ./frontend
    ports:
      - "8888:8888"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000

volumes:
  postgres_data:
  static_volume:
