version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kanastra
      POSTGRES_USER: kanastra
      POSTGRES_PASSWORD: kanastra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=kanastra
      - DATABASE_USER=kanastra
      - DATABASE_PASSWORD=kanastra
      - DATABASE_PORT=5432

  frontend:
    build: ./frontend
    ports:
      - "8888:8888"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data:
